# This is a basic workflow to help you get started with Actions

name: HEXO CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Golang ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          node-version: ${{ matrix.go-version }}

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_KEY}}
        run: |
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "pigLoveRabit"
          git config --global user.email "1906747819@qq.com"

      - name: Install dependencies
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.120.3/hugo_0.120.3_linux-amd64.deb
          sudo dpkg -i hugo*.deb
          hugo version

      - name: Hugo publish
        run: |
          git clone https://github.com/dillonzq/LoveIt.git themes/LoveIt
          hugo

      - name: Upload to qiniu
        working-directory: .
        run: |
          work_path=$(pwd)
          sudo curl -L http://file.51lucy.com/qshell -o /usr/local/bin/qshell
          sudo chmod +x /usr/local/bin/qshell
          qshell account ${{secrets.QINIU_AK}} ${{secrets.QINIU_SK}} meng
          qshell listbucket blog-cn -o ~/blog-cn.list.txt
          qshell batchdelete --force blog-cn -i ~/blog-cn.list.txt
          echo -e "{ \"src_dir\": \"${work_path}/public\", \n \"bucket\": \"blog-cn\" }" > ~/upload.conf
          pwd && qshell -c 5 qupload ~/upload.conf
