# This is a basic workflow to help you get started with Actions

name: HEXO CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.x]

    steps:
      - uses: actions/checkout@v3
      # - name: Configuration environment
      #   env:
      #     HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_KEY}}
      #   run: |
      #     mkdir -p ~/.ssh/
      #     echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa
      #     ssh-keyscan github.com >> ~/.ssh/known_hosts
      #     git config --global user.name "pigLoveRabit"
      #     git config --global user.email "1906747819@qq.com"

      - name: Hugo prepare
        run: |
          git clone https://github.com/dillonzq/LoveIt.git themes/LoveIt

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@v2.2.0
        env:
          HUGO_VERSION: 0.128.0
          TARGET_REPO: pigLoveRabbit520/pigLoveRabbit520.github.io
          TARGET_BRANCH: main
          TOKEN: ${{ secrets.HEXO_DEPLOY_KEY }}
          HUGO_ARGS: ""
          CNAME: blog.51lucy.com
